var files =
[
    [ "area_metodos.c", "area__metodos_8c.html", "area__metodos_8c" ],
    [ "area_metodos.h", "area__metodos_8h.html", null ],
    [ "bridge_arquivosinstrucoes.h", "bridge__arquivosinstrucoes_8h.html", null ],
    [ "carregamento.c", "carregamento_8c.html", "carregamento_8c" ],
    [ "carregamento.h", "carregamento_8h.html", "carregamento_8h" ],
    [ "cast.h", "cast_8h.html", "cast_8h" ],
    [ "classloader.c", "classloader_8c.html", "classloader_8c" ],
    [ "classloader.h", "classloader_8h.html", "classloader_8h" ],
    [ "comparacao.h", "comparacao_8h_source.html", null ],
    [ "const.h", "const_8h.html", "const_8h" ],
    [ "heap.c", "heap_8c.html", "heap_8c" ],
    [ "heap.h", "heap_8h.html", null ],
    [ "ifs.h", "ifs_8h.html", "ifs_8h" ],
    [ "impressao.c", "impressao_8c.html", "impressao_8c" ],
    [ "impressao.h", "impressao_8h.html", "impressao_8h" ],
    [ "load.h", "load_8h.html", "load_8h" ],
    [ "logico_aritimeticas.h", "logico__aritimeticas_8h_source.html", null ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "others.h", "others_8h.html", "others_8h" ],
    [ "pilha_frames.c", "pilha__frames_8c.html", "pilha__frames_8c" ],
    [ "pilha_frames.h", "pilha__frames_8h.html", null ],
    [ "pilha_operandos.c", "pilha__operandos_8c.html", "pilha__operandos_8c" ],
    [ "pilha_operandos.h", "pilha__operandos_8h.html", "pilha__operandos_8h" ],
    [ "pop_dup_swap.h", "pop__dup__swap_8h.html", "pop__dup__swap_8h" ],
    [ "store.h", "store_8h_source.html", null ]
];